202603260817 - Fixed and updated tests for version score function; work in progress for version compare function

diff --git a/tests/scratch b/tests/scratch
--- a/tests/scratch
+++ b/tests/scratch
@@ -7,6 +7,7 @@ YELLOW='\033[1;33m' # Warning
 CYAN='\033[0;36m' # In progress
 GREEN='\033[1;32m' # Success
 NC='\033[0m' # No color
+ERROR_STRING="Err"
 
 documentation() {
   echo "-----------------------------------------------------"
@@ -34,29 +35,38 @@ ask_confirmation() { # Ask for user confirmation, no enter required
 }
 
 get_version_score() { # Parse the version string and calculate the score, with: major version x1000000, feature version x 1000, fixes x 1, allowing for up to vX.999.999. Ignores alpha, (-alpha), beta (-beta), release candidates (-rc) etc
+  if [[ -z "$ERROR_STRING" ]]; then
+    ERROR_STRING="Err"
+  fi
+  local VERSION DIGITS OLDIFS SCORE
   if [[ -z "$1" ]];then # Check for empty or no argument supplied
     echo -e "${RED}Version arguments are missing. You need to provide a version string of form \"v0.0.0\"${NC}" >&2
-    echo "e"
+    echo "$ERROR_STRING"
     return 1
   fi
   if [[ "${#@}" -gt 1 ]];then # Check for more than 1 argument supplied
     echo -e "${RED}Too many version arguments provided. You need to provide only 1 version strings${NC}" >&2
-    echo "e"
+    echo "$ERROR_STRING"
     return 1
   fi
-  if [[ ! "$1" =~ ^[v]?[0-9]+\.[0-9]+\.[0-9]+[\-]?[\-\.0-9a-zA-Z]?+$ ]]; then
+  VERSION="$(cut -d '-' -f 1 <<< $1)"
+  if [[ "$VERSION" =~ ^[v]?[0-9]+$ ]]; then
+    VERSION="$VERSION"".0.0"
+  fi
+  if [[ "$VERSION" =~ ^[v]?[0-9]+\.[0-9]+$ ]]; then
+    VERSION="$VERSION"".0"
+  fi
+  if [[ ! "$VERSION" =~ ^[v]?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
     echo -e "${RED}You need to provide a version string of form \"v0.0.0\"${NC}" >&2
-    echo "e"
+    echo "$ERROR_STRING"
     return 1
   fi
-  local VERS DIGITS OLDIFS SCORE
-  VERS=$(cut -d "-" -f 1 <<< "$1")
   if [[ "${1:0:1}" == "v" ]]; then # Check for "v" prefix and ignore
-    VERS="${1:1:$(( ${#1}-1 ))}"
+    VERSION="${1:1:$(( ${#1}-1 ))}"
   fi
   OLDIFS=$IFS
   IFS='.'
-  read -r -a DIGITS <<< $VERS
+  read -r -a DIGITS <<< $VERSION
   IFS=$OLDIFS
   SCORE=0 # Initialise and compute score
   SCORE=$(( $SCORE + (( ${DIGITS[0]} * 1000000 )) + (( ${DIGITS[1]} * 1000 )) + (( ${DIGITS[2]} * 1 )) ))
@@ -64,25 +74,26 @@ get_version_score() { # Parse the version string and calculate the score, with: 
   return 0
 }
 
-compare_versions() { # Compare two version strings of form "vX.X.X" or "X.X.X" ("X" is a number), the first version argument being the current and base for comparison. Returns "e" if both versions are equal, "g" if first argument is a more recent version and "l" if it is an older version
+compare_versions() { # Compare two version strings of form "vX.X.X" or "X.X.X" ("X" is a number), the first version argument being the current and base for comparison. Returns "e" if both versions are equal, "g" if first argument is a more recent version and "l" if it is an older version. Returns error string "Err" if arguments are not appropriate
+  if [[ -z "$ERROR_STRING" ]]; then
+    ERROR_STRING="Err"
+  fi
   local SCORE1 SCORE2
-  if [[ -z "$1" || -z "$2" ]];then
-    echo -e "${RED}Version arguments are missing. You need to provide 2 version strings${NC}"
+  if [[ -z "$1" || -z "$2" || ${#@} -gt 2 ]];then
+    echo -e "${RED}Version arguments are not adequate. You need to provide 2 version strings of form 'vX.X.X' or 'X.X.X'${NC}" >&2
+    echo "$ERROR_STRING"
     return 1
   fi
   if [[ "$1" =~ ^[v]?[0-9]+\.[0-9]+\.[0-9]+[\-]?[\-\.0-9a-zA-Z]?+$  && "$2" =~ ^[v]?[0-9]+\.[0-9]+\.[0-9]+[\-]?[\-\.0-9a-zA-Z]?+$ ]]; then
     SCORE1=$(get_version_score $1)
-    if [[ ! "$?" == 0 ]];then
-      echo -e "${RED}Version arguments are wrong. You need to provide 2 version strings of form \"vX.X.X\" or \"X.X.X\" (X is a number)${NC}"
-      return 1
-    fi
     SCORE2=$(get_version_score $2)
-    if [[ ! "$?" == 0 ]];then
-      echo -e "${RED}Version arguments are wrong. You need to provide 2 version strings of form \"vX.X.X\" or \"X.X.X\" (X is a number)${NC}"
+    if [[ "$SCORE1" == "$ERROR_STRING" || "$SCORE2" == "$ERROR_STRING" ]];then
+      echo -e "${RED}Version arguments are malformed. You need to provide 2 version strings of form 'vX.X.X' or 'X.X.X' (X is a number)${NC}" >&2
+      echo "$ERROR_STRING"
       return 1
     fi
-    echo $SCORE1
-    echo $SCORE2
+    # echo $SCORE1 >&2
+    # echo $SCORE2 >&2
     if [[ "$SCORE1" -eq "$SCORE2" ]];then
       echo "e"
       return 0
@@ -98,7 +109,8 @@ compare_versions() { # Compare two version strings of form "vX.X.X" or "X.X.X" (
     fi
 
   else
-    echo -e "${RED}Invalid version arguments supplied${NC}"
+    echo -e "${RED}Invalid version arguments supplied${NC}" >&2
+    echo "$ERROR_STRING"
     return 1
   fi
 }
@@ -154,5 +166,6 @@ erase_line() {
 
 # documentation
 #enable_bash_customisations
-#compare_versions "v1.1.1.0" "v10000.0.1"
 #source ./unit_tests/test_get_version_score.sh
+source ./unit_tests/test_compare_versions.sh
+#get_version_score '1-rc2.3'
