202606140825 - Reorganising scripts; inlcuding installation for Android Cuttlefish (work in progress); polished installation for KVM/QEMU and Docker; split outputting functions to new messages.sh library; added the run_and_log function

diff --git a/tests/scratch b/tests/scratch
--- a/tests/scratch
+++ b/tests/scratch
@@ -4,18 +4,6 @@
 source ../lib/functions.sh
 define_font_colours
 
-recho() {
-  echo -e "${RED}$1${NC}"
-}
-
-yecho() {
-  echo -e "${YELLOW}$1${NC}"
-}
-
-gecho() {
-  echo -e "${GREEN}$1${NC}"
-}
-
 documentation() {
   echo "-----------------------------------------------------"
   echo "|               Welcome to Uboontup !               |"
@@ -138,49 +126,37 @@ edit_line() { # Edit a line in a file. A wrapper around the sed function, taking
 }
 
 test_scan(){ # This function will scan through a .tst file for test variables. The first line give the function name, the second a general description and subsequent lines will list results and arguments in test> result> val <result arg> arg <arg <test. All the fields are described in a simple markup format tag>value<tag
-  if [[ -z "$ERROR_STRING" ]]; then
+  if [[ -z "${ERROR_STRING}" ]]; then
     ERROR_STRING="Err"
   fi
   if [[ "$#" -ne 1 ]]; then
-    echo "$ERROR_STRING"
-    recho "${RED}This function requires exactly 1 argument${NC}" >&2
+    echo "${ERROR_STRING}"
+    recho "This function requires exactly 1 argument" >&2
     return 1
   fi
 
-  local lines line func desc current_tag current_value multiline
+  local lines line current_line func desc current_var multiline
   local test=()
   read -r -a lines <<< $(wc -l $1)
-  lines=$(( 1 + "$lines" - 1 ))
-  echo "${lines[0]}"
+  lines=$(( 0 + "${lines}" ))
+  echo "TOTAL LINES: ${lines[0]}"
 
-  line=0
+  current_line=0
   OLDIFS=$IFS
   multiline=1
   while IFS= read -r line; do
-    if [[ "$multiline" == 1 && "${line:0:1}" == '#' || "$line" == "" || "$line" == " " ]]; then
+    echo "${line:$(( ${#line} -1 ))}"
+    # if [[ "$line{$(( line[#] - 1 ))}" == "\" ]]
+    #   echo "MULTILINE"
+    # fi
+    IFS="=" read -r -a current_var
+    if [[ "${multiline}" -eq 1 && "${line:0:1}" == '#' || "${line}" == "" || "${line}" == " " ]]; then
       continue
+    else
+      current_line=$(( ${current_line} + 1 ))
+      echo "${current_line}: ${line}"
+      echo "${current_var[@]}"
     fi
-    if [[ "$multiline" == 0 ]]; then
-      if [[ "${line:0:1}" == '<' || "$line" == "" || "$line" == " " ]]; then
-        multiline=1
-        continue
-      fi
-    fi
-    for (( i=0; i<${#line}; i++ )); do
-      if [[ "${line:$i:1}" == ">" ]]; then
-        break
-      fi
-      current_tag+="${line:$i:1}"
-    done
-    current_value="${line#*>}"
-    current_value="${current_value%<$current_tag*}"
-    if [[ -z "$current_value"]]; then
-      multiline=0
-      continue
-    fi
-    echo "Tag: $current_tag, Value: $current_value"
-    current_tag=""
-    current_value=""
   done < example.tst
 }
 
@@ -191,4 +167,20 @@ test_scan(){ # This function will scan through a .tst file for test variables. T
 #source ./unit_tests/test_get_version_score.sh
 #source ./unit_tests/test_edit_line.sh
 #edit_line 'c\(o\?d\?\)e' 'test' 'sc_test' -v
-test_scan example.tst
+# test_scan example.tst
+
+# for (( i=0; i<${#line}; i++ )); do
+#       if [[ "${line:$i:1}" == ">" ]]; then
+#         break
+#       fi
+#       current_tag+="${line:$i:1}"
+#     done
+#     current_value="${line#*>}"
+#     current_value="${current_value%<$current_tag*}"
+#     if [[ -z "$current_value" ]]; then
+#       multiline=0
+#       continue
+#     fi
+#     echo "Tag: $current_tag, Value: $current_value"
+#     current_tag=""
+#     current_value=""
