202607221303 - Further works on detection of bash customisations

diff --git a/tests/scratch b/tests/scratch
--- a/tests/scratch
+++ b/tests/scratch
@@ -4,183 +4,221 @@
 source ../lib/functions.sh
 define_font_colours
 
-documentation() {
-  echo "-----------------------------------------------------"
-  echo "|               Welcome to Uboontup !               |"
-  echo "|                                                   |"
-  echo "|      An easy way to get Ubuntu up and running     |"
-  echo "|               for some serious work               |"
-  echo "-----------------------------------------------------"
-
-}
-
-enable_bash_customisations() { # Check .bashrc and source for customisation files
+check_bash_customisations() { # Check .bashrc and source for customisation files
   if [[ -z "$ERROR_STRING" ]]; then
     ERROR_STRING="Err"
   fi
-  #local BASHRC_FILE="$HOME/.bashrc_test"
-  local BASHRC_FILE="./sc_test"
-  local CUSTOM_FILE='../custom/uboontup_aliases_and_functions'
-  local RGX='source .*uboontup_aliases_and_functions'
-  #local LINE='source ../uboontup_aliases_and_functions'
-  #local INSERT=""
-  local VERSION=$(sed -n 's/.*\(## Uboontup Version: \)\([v\.0-9]*\).*/\2/p' "$CUSTOM_FILE")
-  local SOURCES=$(sed -n "/$RGX/p" "$BASHRC_FILE"|wc -l)
-  if [[ -f "$BASHRC_FILE" ]]; then
-    if [[ ! -z "$TEMP" ]]; then
-      echo -e "${YELLOW}Bash customisations found${NC}"
-      return 0
-    fi
-    if [[ "$(ask_confirmation 'Install bash aliases and helper functions to your .bashrc?')" == "y" ]]; then
-      echo
-      INSERT="\n## Bash customisations (v0.1): aliases and functions\n$LINE"
-      echo -e "$INSERT" >> "$BASHRC_FILE"
-    else
-      echo
-      return 0
-    fi
-  else
-    local ERROR_MESSAGE=".bashrc file not found"
-    echo -e "${RED}$ERROR_MESSAGE${NC}" >&2
-    echo "Please check that you have Bash installed and configured correctly" >&2
-    critical_error "$ERROR_MESSAGE"
-    return 1
-  fi
-    # get custom file version
-    # if version != current
-      # propose to replace lines and file
-  # else
-    # propose to install
-}
-
-edit_line() { # Edit a line in a file. A wrapper around the sed function, taking a search string and replacing it with another insert string in a file. Accepts 3 arguments: 1. the search string; 2. the replacement string; 3. the file to edit. Uses grep with basic regex for line search under the hood and sed for replacement. Returns the number of matches found. Options are: -v (verbose and interactive) to print matches and replacement and require confirmation for replacement; -s (single) for replacement of a single instance of pattern, shifting to interactive mode if multiple instances are found.
-  if [[ -z "$ERROR_STRING" ]]; then
-    ERROR_STRING="Err"
-  fi
-  if [[ "$#" -lt 3 ]]; then
-    recho "This function requires at least 3 arguments" >&2
-    echo "$ERROR_STRING"
-    return 1
-  fi
-  local MODE="n"
-  if [[ $4 == "-s" || $5 == "-s" ]]; then
-    MODE="s"
-  fi
-  if [[ $4 == "-v" || $5 == "-v" ]]; then
-    MODE="v"
-  fi
-  if [[ ! -f $3 ]]; then
-    recho "$3 is not a regular file" >&2
-    echo "$ERROR_STRING"
-    return 1
-  fi
-  local LINE_NUM SEARCH REPLACE NEW_LINE MATCHES CONF REPLACEMENTS
-  SEARCH="$1"
-  if [[ "$SEARCH" == "\n" ]]; then
-    SEARCH=$'\n'
-  fi
-  REPLACE="$2"
-  local LINES="$(grep $SEARCH $3)"
-  OLD_IFS=$IFS; IFS=$'\n'; LINES=($LINES); IFS=$OLD_IFS
-  MATCHES="${#LINES[@]}"
-  if [[ "$MATCHES" -eq 0 ]]; then
-    yecho "No match found in file" >&2
-    echo "$MATCHES"
-    return 0
-  fi
-  if [[ "$MODE" == 'v' ]]; then
-    echo "Matches found:" >&2
-    for i in "${!LINES[@]}"; do
-      echo "$(( $i + 1 )). ${LINES[$i]}" >&2
-    done
-  fi
-  REPLACEMENTS=0
-  for item in "${LINES[@]}"; do
-    NEW_LINE=$(sed -n "s/${SEARCH//\//\\/}/${REPLACE//\//\\/}/p" <<< "${item}")
-    CONF='y'
-    if [[ "$MODE" == 'v' || "$MODE" == "s" ]]; then
-      yecho "=====================" >&2
-      yecho "Before Edit" >&2
-      echo "${item}" >&2
-      yecho "After Edit" >&2
-      echo "${NEW_LINE}" >&2
-      yecho "=====================" >&2
-      CONF=$(ask_confirmation)
-    fi
-    if [[ "$CONF" == 'y' ]]; then
-      REPLACEMENTS="$(( ${REPLACEMENTS} + 1 ))"
-      sed -i "s/${item//\//\\/}/${NEW_LINE//\//\\/}/" $3
-      echo >&2
-      if [[ "$MODE" == 's' ]]; then
-        break
-      fi
-    else
-      MATCHES="$(( ${MATCHES} - 1 ))"
-      echo >&2
-    fi
-  done
-  #cat $3 >&2
-  echo >&2
-  echo "${REPLACEMENTS}"
-  cp sc_test.bak sc_test
-}
-
-test_scan(){ # This function will scan through a .tst file for test variables. The first line give the function name, the second a general description and subsequent lines will list results and arguments in test> result> val <result arg> arg <arg <test. All the fields are described in a simple markup format tag>value<tag
-  if [[ -z "${ERROR_STRING}" ]]; then
-    ERROR_STRING="Err"
-  fi
-  if [[ "$#" -ne 1 ]]; then
+  if [[ "$#" -gt 1 ]]; then
     echo "${ERROR_STRING}"
-    recho "This function requires exactly 1 argument" >&2
+    recho "This function requires at most 1 argument" >&2
     return 1
   fi
-
-  local lines line current_line func desc current_var multiline
-  local test=()
-  read -r -a lines <<< $(wc -l $1)
-  lines=$(( 0 + "${lines}" ))
-  echo "TOTAL LINES: ${lines[0]}"
-
-  current_line=0
-  OLDIFS=$IFS
-  multiline=1
-  while IFS= read -r line; do
-    echo "${line:$(( ${#line} -1 ))}"
-    # if [[ "$line{$(( line[#] - 1 ))}" == "\" ]]
-    #   echo "MULTILINE"
-    # fi
-    IFS="=" read -r -a current_var
-    if [[ "${multiline}" -eq 1 && "${line:0:1}" == '#' || "${line}" == "" || "${line}" == " " ]]; then
-      continue
-    else
-      current_line=$(( ${current_line} + 1 ))
-      echo "${current_line}: ${line}"
-      echo "${current_var[@]}"
-    fi
-  done < example.tst
+  if [[ -n "$1" && "$1" != "-t" && "$2" != "-t" ]]; then
+    BASHRC_FILE="$1"
+  else
+    BASHRC_FILE="$HOME/.bashrc"
+  fi
+  if [[ ! -f "$BASHRC_FILE" ]]; then
+    echo "${ERROR_STRING}"
+    recho "No default or custom .bashrc file found" >&2
+    return 1
+  fi
+  if [[ ! -d "$HOME/.config/uboontup" || ! -f "$HOME/.config/uboontup/uboontup.conf" ]];then
+    echo "${ERROR_STRING}"
+    recho "No uboontup config directory or file found at $HOME/.config/" >&2
+    return 1
+  fi
+  if [[ $1 == "-t" || $2 == "-t" ]]; then
+    yecho "Testing mode:" >&2
+  fi
+  return 0
 }
 
-#documentation
-#enable_bash_customisations
-#source ./unit_tests/test_check_customisations.sh
-#source ./unit_tests/test_edit_line.sh
-#source ./unit_tests/test_get_version_score.sh
-#source ./unit_tests/test_edit_line.sh
-#edit_line 'c\(o\?d\?\)e' 'test' 'sc_test' -v
-# test_scan example.tst
+# check_regular_file() { # Check if a file exists and is a regular file. Accepts 1 argument: the file to check. Returns 0 if the file exists and is a regular file, 1 otherwise.
+#   if [[ -z "$ERROR_STRING" ]]; then
+#     ERROR_STRING="Err"
+#   fi
+#   if [[ "$#" -ne 1 ]]; then
+#     echo "${ERROR_STRING}"
+#     recho "This function requires exactly 1 argument" >&2
+#     return 1
+#   fi
+#   if [[ ! -f "$1" ]]; then
+#     echo "${ERROR_STRING}"
+#     recho "$1 is not a regular file" >&2
+#     return 1
+#   fi
+#   return 0
+# }
 
-# for (( i=0; i<${#line}; i++ )); do
-#       if [[ "${line:$i:1}" == ">" ]]; then
+# edit_line() { # Edit a line in a file. A wrapper around the sed function, taking a search string and replacing it with another insert string in a file. Accepts 3 arguments: 1. the search string; 2. the replacement string; 3. the file to edit. Uses grep with basic regex for line search under the hood and sed for replacement. Returns the number of matches found. Options are: -v (verbose and interactive) to print matches and replacement and require confirmation for replacement; -s (single) for replacement of a single instance of pattern, shifting to interactive mode if multiple instances are found.
+#   if [[ -z "$ERROR_STRING" ]]; then
+#     ERROR_STRING="Err"
+#   fi
+#   if [[ "$#" -lt 3 ]]; then
+#     recho "This function requires at least 3 arguments" >&2
+#     echo "$ERROR_STRING"
+#     return 1
+#   fi
+#   local MODE="n"
+#   if [[ $4 == "-s" || $5 == "-s" ]]; then
+#     MODE="s"
+#   fi
+#   if [[ $4 == "-v" || $5 == "-v" ]]; then
+#     MODE="v"
+#   fi
+#   if [[ ! $(check_regular_file "$3") ]]; then
+#     return 1
+#   fi
+#   local LINE_NUM SEARCH REPLACE NEW_LINE MATCHES CONF REPLACEMENTS
+#   SEARCH="$1"
+#   if [[ "$SEARCH" == "\n" ]]; then
+#     SEARCH=$'\n'
+#   fi
+#   REPLACE="$2"
+#   local LINES="$(grep $SEARCH $3)"
+#   OLD_IFS=$IFS; IFS=$'\n'; LINES=($LINES); IFS=$OLD_IFS
+#   MATCHES="${#LINES[@]}"
+#   if [[ "$MATCHES" -eq 0 ]]; then
+#     yecho "No match found in file" >&2
+#     echo "$MATCHES"
+#     return 0
+#   fi
+#   if [[ "$MODE" == 'v' ]]; then
+#     echo "Matches found:" >&2
+#     for i in "${!LINES[@]}"; do
+#       echo "$(( $i + 1 )). ${LINES[$i]}" >&2
+#     done
+#   fi
+#   REPLACEMENTS=0
+#   for item in "${LINES[@]}"; do
+#     NEW_LINE=$(sed -n "s/${SEARCH//\//\\/}/${REPLACE//\//\\/}/p" <<< "${item}")
+#     CONF='y'
+#     if [[ "$MODE" == 'v' || "$MODE" == "s" ]]; then
+#       yecho "=====================" >&2
+#       yecho "Before Edit" >&2
+#       echo "${item}" >&2
+#       yecho "After Edit" >&2
+#       echo "${NEW_LINE}" >&2
+#       yecho "=====================" >&2
+#       CONF=$(ask_confirmation)
+#     fi
+#     if [[ "$CONF" == 'y' ]]; then
+#       REPLACEMENTS="$(( ${REPLACEMENTS} + 1 ))"
+#       sed -i "s/${item//\//\\/}/${NEW_LINE//\//\\/}/" $3
+#       echo >&2
+#       if [[ "$MODE" == 's' ]]; then
 #         break
 #       fi
-#       current_tag+="${line:$i:1}"
-#     done
-#     current_value="${line#*>}"
-#     current_value="${current_value%<$current_tag*}"
-#     if [[ -z "$current_value" ]]; then
-#       multiline=0
-#       continue
+#     else
+#       MATCHES="$(( ${MATCHES} - 1 ))"
+#       echo >&2
 #     fi
-#     echo "Tag: $current_tag, Value: $current_value"
-#     current_tag=""
-#     current_value=""
+#   done
+#   #cat $3 >&2
+#   echo >&2
+#   echo "${REPLACEMENTS}"
+#   cp sc_test.bak sc_test
+# }
+
+# test_scan(){ # This function will scan through a .tst file for test variables. The first line give the function name, the second a general description and subsequent lines will list results and arguments in test> result> val <result arg> arg <arg <test. All the fields are described in a simple markup format tag>value<tag
+#   if [[ -z "${ERROR_STRING}" ]]; then
+#     ERROR_STRING="Err"
+#   fi
+#   if [[ "$#" -ne 1 ]]; then
+#     echo "${ERROR_STRING}"
+#     recho "This function requires exactly 1 argument" >&2
+#     return 1
+#   fi
+
+#   local lines line current_line func desc current_var multiline
+#   local test=()
+#   read -r -a lines <<< $(wc -l $1)
+#   lines=$(( 0 + "${lines}" ))
+#   echo "TOTAL LINES: ${lines[0]}"
+
+#   current_line=0
+#   OLDIFS=$IFS
+#   multiline=1
+#   while IFS= read -r line; do
+#     echo "${line:$(( ${#line} -1 ))}"
+#     # if [[ "$line{$(( line[#] - 1 ))}" == "\" ]]
+#     #   echo "MULTILINE"
+#     # fi
+#     IFS="=" read -r -a current_var
+#     if [[ "${multiline}" -eq 1 && "${line:0:1}" == '#' || "${line}" == "" || "${line}" == " " ]]; then
+#       continue
+#     else
+#       current_line=$(( ${current_line} + 1 ))
+#       echo "${current_line}: ${line}"
+#       echo "${current_var[@]}"
+#     fi
+#   done < example.tst
+# }
+
+# #documentation
+# #enable_bash_customisations
+source ./unit_tests/test_check_customisations.sh
+# #source ./unit_tests/test_edit_line.sh
+# check_regular_file "./sc_test"
+# check_regular_file "./unit_tests/test_edit_line.sh"
+# check_regular_file "./some.file"
+# check_regular_file "./test_home"
+# #source ./unit_tests/test_get_version_score.sh
+# #source ./unit_tests/test_edit_line.sh
+# #edit_line 'c\(o\?d\?\)e' 'test' 'sc_test' -v
+# # test_scan example.tst
+
+# # for (( i=0; i<${#line}; i++ )); do
+# #       if [[ "${line:$i:1}" == ">" ]]; then
+# #         break
+# #       fi
+# #       current_tag+="${line:$i:1}"
+# #     done
+# #     current_value="${line#*>}"
+# #     current_value="${current_value%<$current_tag*}"
+# #     if [[ -z "$current_value" ]]; then
+# #       multiline=0
+# #       continue
+# #     fi
+# #     echo "Tag: $current_tag, Value: $current_value"
+# #     current_tag=""
+# #     current_value=""
+
+
+# if [[ -z "$ERROR_STRING" ]]; then
+#     ERROR_STRING="Err"
+#   fi
+#   #local BASHRC_FILE="$HOME/.bashrc_test"
+#   local BASHRC_FILE="./sc_test"
+#   local CUSTOM_FILE='../custom/uboontup_aliases_and_functions'
+#   local RGX='source .*uboontup_aliases_and_functions'
+#   #local LINE='source ../uboontup_aliases_and_functions'
+#   #local INSERT=""
+#   local VERSION=$(sed -n 's/.*\(## Uboontup Version: \)\([v\.0-9]*\).*/\2/p' "$CUSTOM_FILE")
+#   local SOURCES=$(sed -n "/$RGX/p" "$BASHRC_FILE"|wc -l)
+#   if [[ -f "$BASHRC_FILE" ]]; then
+#     if [[ ! -z "$TEMP" ]]; then
+#       echo -e "${YELLOW}Bash customisations found${NC}"
+#       return 0
+#     fi
+#     if [[ "$(ask_confirmation 'Install bash aliases and helper functions to your .bashrc?')" == "y" ]]; then
+#       echo
+#       INSERT="\n## Bash customisations (v0.1): aliases and functions\n$LINE"
+#       echo -e "$INSERT" >> "$BASHRC_FILE"
+#     else
+#       echo
+#       return 0
+#     fi
+#   else
+#     local ERROR_MESSAGE=".bashrc file not found"
+#     echo -e "${RED}$ERROR_MESSAGE${NC}" >&2
+#     echo "Please check that you have Bash installed and configured correctly" >&2
+#     critical_error "$ERROR_MESSAGE"
+#     return 1
+#   fi
+#     # get custom file version
+#     # if version != current
+#       # propose to replace lines and file
+#   # else
+#     # propose to install
diff --git a/tests/test b/tests/test
--- a/tests/test
+++ b/tests/test
@@ -5,33 +5,38 @@ source ../lib/functions.sh
 # FONT COLORS
 define_font_colours
 
-# VARIABLES
-USER_DIRS=("logs" "repos" "setup")
-USER_FILES=("/logs/init.log" "/logs/errors.log")
-BASE_DIR="$HOME"
-PREV_DIR="$(pwd)"
-WARNINGS=()
-ERRORS=()
+# # VARIABLES
+UBOON_DIR=$(sed -n 's/\(.*[Uu]boontup\).*/\1/p' <<< $(cd $(dirname "${BASH_SOURCE[0]}") && pwd))
+echo "UBOONTUP_DIR=\"$UBOON_DIR\"" > $HOME/.config/uboontup.conf
+# USER_DIRS=("logs" "repos" "setup")
+# USER_FILES=("/logs/init.log" "/logs/errors.log")
+# BASE_DIR="$HOME"
+# PREV_DIR="$(pwd)"
+# WARNINGS=()
+# ERRORS=()
 
-# enable_bash_customisations
-# Execute actions
-set_base_dir
-check_base_dir
-check_base_dir_write
-# check_and_create_dir "${USER_DIRS[@]}"
-# backup_folder "test" "bkp_"
+# # Welcome
+# welcome
 
-cd $PREV_DIR
+# # enable_bash_customisations
+# # Execute actions
+# set_base_dir
+# check_base_dir
+# check_base_dir_write
+# # check_and_create_dir "${USER_DIRS[@]}"
+# # backup_folder "test" "bkp_"
 
-# INSTALL PACKAGES
-sudo apt update
-sudo apt upgrade
-sudo apt install build-essential software-properties-common gcc g++ perl make git  curl wget gpg net-tools zip unzip ffmpeg ufw openssl dkms  ubuntu-restricted-extras  python3 htop tmux
+# cd $PREV_DIR
 
-if [[ $PREV_DIR == $(pwd) ]]; then
-  echo -e "${GREEN}Thank you for using Uboontup. We hope you had a nice experience.${NC}"
-  exit 0;
-else
-  echo -e "${RED}We are sorry, but something went wrong.${NC} File an issue or contact us on ${YELLOW}Github${NC} for further assistance."
-  exit 1
-fi
+# # INSTALL PACKAGES
+# sudo apt update
+# sudo apt upgrade
+# sudo apt install build-essential software-properties-common gcc g++ perl make git  curl wget gpg net-tools zip unzip ffmpeg ufw openssl dkms  ubuntu-restricted-extras  python3 htop tmux
+
+# if [[ $PREV_DIR == $(pwd) ]]; then
+#   echo -e "${GREEN}Thank you for using Uboontup. We hope you had a nice experience.${NC}"
+#   exit 0;
+# else
+#   echo -e "${RED}We are sorry, but something went wrong.${NC} File an issue or contact us on ${YELLOW}Github${NC} for further assistance."
+#   exit 1
+# fi
